name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.4"

    # 3. Install system dependencies for Qt and EGL
    - name: Install system dependencies for Qt and EGL
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxkbcommon-x11-0 \
          libxcb-xinerama0 \
          libxcb-xinput0 \
          libxcb-cursor0 \
          libxkbcommon0 \
          libgl1-mesa-glx \
          libegl1 \
          libegl-mesa0 \
          libxcb-render0 \
          libxcb-shape0 \
          libxcb-sync1 \
          libfontconfig1 \
          libx11-xcb1

    # 4. Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 5. Run tests
    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "*.py"
