name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.4"

    # 3. Install system dependencies for Qt and EGL
    - name: Install system dependencies for Qt and EGL
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          # XCB, X11 and related libraries for Qt support
          libx11-xcb1 \
          libxkbcommon-x11-0 \
          libxcb-cursor0 \
          libxcb-dri3-0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-present0 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-render0 \
          libxcb-shape0 \
          libxcb-shm0 \
          libxcb-sync1 \
          libxcb-util1 \
          libxcb-xfixes0 \
          libxcb-xinerama0 \
          libxcb-xkb1 \
          # EGL and OpenGL for rendering
          libegl1 \
          libegl-mesa0 \
          libgl1-mesa-glx \
          # Font and text rendering
          libfontconfig1 \
          libfreetype6 \
          # Miscellaneous dependencies
          libx11-6 \
          libxext6 \
          libxrender1 \
          libxi6 \
          libsm6 \
          libice6 \
          # Additional dependencies for PyQt6
          libxss1 \
          libxtst6 \
          libatspi2.0-0 \
          libdbus-1-3 \
          libgdk-pixbuf2.0-0 \
          libxft2 \
          # Mesa dependencies for graphics rendering
          libglu1-mesa \
          libxmu6

    # 4. Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 5. Run tests
    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "*.py"