name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Install system libraries
    - name: Install system libraries for PyQt6
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libegl1-mesa \
          libgbm-dev \
          libxcb-cursor0 \
          libxcb-xinerama0 \
          libxkbcommon-x11-0 \
          libglu1-mesa \
          libx11-xcb-dev \
          libxrender1 \
          libxi6 \
          xvfb

    # 3. Set up X virtual framebuffer
    - name: Start xvfb
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 &

    # 4. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 5. Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 6. Run tests
    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "*.py"
