name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Install system dependencies
    - name: Install system libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1 libglib2.0-0

    # 3. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 4. Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 5. Run tests
    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "*.py"
